### ISSUE TITLE
tf2::BufferCore implementation of lookupTransform can't specify lookup duration in Foxy

### ISSUE THREAD

**Issue by jilaada** [tier4/Pilot.Auto#23]
What should be the new method of looking up transform with a given timeout. With the current implementation of BufferCore, this cannot be achieved ([see the doxygen for information](http://docs.ros2.org/foxy/api/tf2/classtf2_1_1BufferCore.html#a5d578ecbea2ec0fdb92de1616251e175)). However the implementation provided by tf2::BufferClient allows for a timeout duration to be specified ([see the doxygen for information](http://docs.ros2.org/foxy/api/tf2_ros/classtf2__ros_1_1Buffer.html#a3ab502cc1e8b608957a96ad350815aee)).

It would be ok, to ignore the timeout duration in transform lookups using the current time, however some methods use the message time stamp which might result in errors due to latency.

**Comment by TakaHoribe** [comment]
I tried to use the implementation like this

```
transform = tf_buffer_->lookupTransform(
       "map", "base_link", tf2::TimePointZero, tf2::durationFromSec(timeout_sec));
```

then, got this error.

```
Do not call canTransform or lookupTransform with a timeout unless you are using another thread for populating data. 
Without a dedicated thread it will always timeout. 
If you have a seperate thread servicing tf messages, call setUsingDedicatedThread(true) on your Buffer instance.
```

**Comment by jilaada** [comment]
@TakaHoribe Thanks for sharing this, I might have a look at the implementation and see if there have been any design decisions to stop support in feature as Mitsudome-san has suggested in the meeting yesterday.

**Comment by nnmm** [comment]
We had a broader discussion around the topic of waiting for transforms here: https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/644. It was the same pattern of getting a message, and then checking TF for a transform with the timestamp of the message. My understanding, also after talking with Chris, is that a proper solution would need to explicitly subscribe to `/tf` and have a combined callback, similar to `message_filters`.

But that's not very helpful in the short term – maybe `waitForTransform` doesn't suffer from the problem Taka posted about and can be used. We haven't tried it in AutowareAuto since we were still on Dashing.

**Comment by jilaada** [comment]
Thanks great! Thanks for doing that investigation. I'll use this in the `multi_object_tracker` implementation. I'll go ahead and close this issue. Maybe we should add this information to the `porting_to_ros2` readme? @nnmm

**Comment by nnmm** [comment]
@TakaHoribe Going back to this, I couldn't reproduce the error message in your comment https://github.com/tier4/pilot.auto/issues/23#issuecomment-708116278. Could you provide a code example?
