### ISSUE TITLE
Issues with porting packages with topic_tools dependencies

### ISSUE THREAD

**Issue by jilaada** [tier4/Pilot.Auto#82]
## Sumary

The topic tools package is used by a couple of different packages within this repository, specifically `ShapeShifter` and relay topics. Currently the `topic_tools` package is not ported. I've been following the (rather) recent discussion on getting topic_tools ported but it seems like something that might not be easily achieved:
 * https://discourse.ros.org/t/ros2-anything-equivalent-to-topic-tools-shapeshifter/3393
 * https://github.com/ros2/ros2/issues/857

It package topics_tools appears to be used in the following packages (other than `autoware_state_monitor`) but only as part of the launch file:
1. `autoware_state_monitor` - ShapeShifter
2. `awapi_awiv_adapter` - relay nodes
3. `scenario_selector` - relay nodes
4. `simple_planning_simulator`  - relay nodes

Potential work around so far can be to use `GenericSubscription` part of `ros2bag_transport` as an example on how to extend the `SubscriptionBase` to suit the simplistic needs of generalising the subscription of topics. Though it seems like there may be many dependencies that over-complicates the package.

For the `autoware_state_monitor` the `GenericSubscription` is sufficient as all that is necessary is collecting the time in which a topic is published to. The data from that topic is irrelevant. Though the ability to know the topic name is important for logging purposes.

## To Do:
- [x] @dejanpan to investigate the state of `topic_tools` porting.
- [x] @nnmm and @mitsudome-r to add any other investigation they have done on the topic.

**Comment by dejanpan** [comment]
The problem here is the following:
1. In ROS1 when you did something like this: https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/src/relay.cpp#L58, which is then used like this https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/src/relay.cpp#L81-L84, it meant that you got the data on the topic without knowing the type of the data which is then needed for the serialization. In ROS1 the node would then communicate with the `rosmaster` (which acts as a DNS) and that would return back the type and the de-serialization would then be possible. That was kind of magic because it would even work if you did not have code compiled locally, which is what William is saying here: https://github.com/ros2/ros2/issues/857#issuecomment-577277416
1. In ROS 2 we do not have this functionality but what we have is https://github.com/ros2/rosbag2/blob/c34601acba77d08c22211d3eb062b8ba867fef71/rosbag2_transport/src/rosbag2_transport/generic_subscription.hpp#L28-L34 which is used e.g. like this https://github.com/ros2/rosbag2/blob/91bf0bf85d84d3bb7ebb54e78b52fedc8e0be780/rosbag2_transport/src/rosbag2_transport/recorder.cpp#L163-L166. 
    1. It works if the type support for the type and matching rmw implementation is built locally and accessible to the current process (via the ament index I think). I think it opens the type support library with dlopen to access the rmw message type support structure it needs.
    1. What this means is that we will have to do one additional task compare to ROS1, that is to  specify a string with the topic type in addition  to the topic name
    1. This will allow us to port everything in here https://github.com/ros/ros_comm/tree/noetic-devel/tools/topic_tools/src
1. What will not be able to do is https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/scripts/relay_field and https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/scripts/transform. For this task we would need something like this https://github.com/facontidavide/ros2_introspection (and I need to admit that I did not 100% understand why).

@nnmm are you gonna take on the task then? The 3 people from here https://github.com/ros2/ros2/issues/857 (emerson, william and michael will technically support you).

**Comment by nnmm** [comment]
@dejanpan Yes, I'll start tomorrow. I think you suggested contributing this to the ROS project – where should the code live? 

At least for `relay`, it seems to me like the result will have at its core parts of the `rosbag2` repo, but with a few headers made public, and a very thin node on top of it.

**Comment by nnmm** [comment]
@jilaada https://github.com/tier4/AutowareArchitectureProposal/pull/118 pulls the `topic_tools` prototype into AutowareArchitectureProposal. See https://github.com/tier4/Pilot.Auto/pull/51/commits/0c6b10982e3b0b8855e99823290e591fba01a0bf#diff-c0131700f2206de527c72b030423e3f45fcd2aa6976b050f0604c174c35f1c03 for an example of how to use it.

**Comment by jilaada** [comment]
I think this issue can be closed as packages that have topic_tools dependencies have been ported.
